# Grafana Provider Creds
apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  namespace: crossplane
type: Opaque
stringData:
  credentials: |
    {
      "url": "https://<your grafana url>",
      "auth": "<token or username:password>"
    }

---

# Grafana Provider
apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: grafana-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: grafana-creds
      namespace: crossplane
      key: credentials

---

# Folder
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: my-folder
spec:
  forProvider:
    title: 'Crossplane Folder Test!'
  providerConfigRef:
    name: grafana-provider

---

# Dashboard
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: my-dashboard
spec:
  forProvider:
    folderRef:
      name: my-folder
    configJson: |
      {
        "title": "Crossplane Test!",
        "uid": "crossplane"
      }
  providerConfigRef:
    name: grafana-provider


