apiVersion: service.grafana.crossplane.io/v1alpha1
kind: Account
metadata:
  name: my-service-account
spec:
  forProvider:
    name: 'Crossplane-test' # unique
    role: 'Admin'
    organizationRef:
      name: "blut-dev"
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: provider-grafana-blut-dev-service-account
    namespace: crossplane-system
---
apiVersion: service.grafana.crossplane.io/v1alpha1
kind: AccountToken
metadata:
  name: my-service-account-token
spec:
  forProvider:
    name: 'blut-dev-test-token' # unique (?)
    serviceAccountRef:
      name: my-service-account
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: provider-grafana-blut-dev-service-account-token
    namespace: crossplane-system